import {CMS_NAME} from "../lib/constants";
import '../styles/index.css'
import React from "react";
import {Navbar} from "../components/navbar";
import Footer from "../components/footer";

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <Navbar activityIndicator={{open: null}}/>
          {/*<Alert preview={preview} />*/}
          <main>{children}</main>
        </div>
        <Footer/>
      </body>
    </html>
  )
}


export const metadata = {
  title: `Next.js Blog Example with ${CMS_NAME}`,
  description: 'Generated by create next app',
}
