version: '3.6'

services:
  # Command line interface to wordpress
  wpcli:
    build: ./wpcli/
    image: wpcli
    environment:
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wordpress}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
    volumes:
      - wordpress:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - wordpress
      - mysql

volumes:
  wordpress:
