version: '3.6'

services:
  # Wordpress cms
  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-latest}
    environment:
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
    volumes:
      - wordpress:/var/www/html
    ports:
      - "${WORDPRESS_PORT}:80"
    depends_on:
      - mysql
      - phpmyadmin
    restart: always

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_USER=${DATABASE_USER:-root}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-password}
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME:-wordpress}
    volumes:
      - wordpress-db:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql
    restart: always


  # Activity indicator
  activity-indicator-kv-interface:
    image: hiett/serverless-redis-http:0.0.8
    environment:
      SRH_MODE: env
      SRH_TOKEN: $KV_REST_API_TOKEN
      SRH_CONNECTION_STRING: 'redis://:${ACTIVITY_INDICATOR_REDIS_PASSWORD}@activity-indicator-db:6379'
    ports:
      - "${ACTIVITY_INDICATOR_KV_PORT}:80"
    depends_on:
      - activity-indicator-db
    restart: always

  activity-indicator-db:
    image: redis:7.2.0
    volumes:
      - activity-indicator-db:/data
    ports:
      - "${ACTIVITY_INDICATOR_REDIS_PORT}:6379"
    command: redis-server --requirepass ${ACTIVITY_INDICATOR_REDIS_PASSWORD}  # user name is "default"
    restart: always

volumes:
  wordpress:
  wordpress-db:
  activity-indicator-db:
